# Generated by Django 2.2.6 on 2019-11-02 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='wellLocation',
        ),
    ]
