# Generated by Django 2.2.6 on 2019-11-02 01:05

from django.db import migrations, models
import lib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_remove_compound_welllocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='zinc_id',
            field=models.CharField(max_length=30, unique=True, validators=[lib.validators.validate_prefix('ZINC'), lib.validators.validate_prefix('zinc')]),
        ),
    ]
