# Generated by Django 2.2.6 on 2019-12-06 00:06

from django.conf import settings
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import s3.models
import s3.s3utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(blank=True, null=True, storage=s3.s3utils.PublicMediaStorage(), upload_to=s3.models.user_file_upload_path)),
                ('local_upload', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=s3.models.upload_local_path)),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('filetype', models.CharField(default='', max_length=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s3_publicfile_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateFileJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('filetype', models.CharField(default='', max_length=5)),
                ('upload', models.FileField(blank=True, null=True, storage=s3.s3utils.PrivateMediaStorage(), upload_to=s3.models.user_file_upload_path, validators=[django.core.validators.FileExtensionValidator(['json'])])),
                ('local_upload', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=s3.models.upload_local_path, validators=[django.core.validators.FileExtensionValidator(['json'])])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s3_privatefilejson_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateFileCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('filetype', models.CharField(default='', max_length=5)),
                ('upload', models.FileField(blank=True, null=True, storage=s3.s3utils.PrivateMediaStorage(), upload_to=s3.models.user_file_upload_path, validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('local_upload', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=s3.models.upload_local_path, validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s3_privatefilecsv_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('local_upload', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=s3.models.upload_local_path)),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('filetype', models.CharField(default='', max_length=5)),
                ('upload', models.FileField(storage=s3.s3utils.PrivateMediaStorage(), upload_to=s3.models.user_file_upload_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s3_privatefile_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='publicfile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, local_upload__in=['', None]), models.Q(_negated=True, upload__in=['', None]), _connector='OR'), name='publicfile_has_upload'),
        ),
        migrations.AddConstraint(
            model_name='privatefilejson',
            constraint=models.CheckConstraint(check=models.Q(('local_upload__in', ['', None]), ('upload__in', ['', None]), _negated=True), name='privatefilejson_has_upload'),
        ),
        migrations.AddConstraint(
            model_name='privatefilejson',
            constraint=models.CheckConstraint(check=models.Q(local_upload__endswith='.json'), name='endswith_json'),
        ),
        migrations.AddConstraint(
            model_name='privatefilecsv',
            constraint=models.CheckConstraint(check=models.Q(('local_upload__in', ['', None]), ('upload__in', ['', None]), _negated=True), name='has_upload'),
        ),
        migrations.AddConstraint(
            model_name='privatefilecsv',
            constraint=models.CheckConstraint(check=models.Q(local_upload__endswith='.csv'), name='endswith_csv'),
        ),
    ]
