# Generated by Django 2.2.2 on 2019-07-30 20:26

from django.db import migrations, models
import s3.models
import s3.s3utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_file', models.FileField(blank=True, null=True, upload_to='open/')),
                ('private_file', s3.models.S3PrivateFileField(blank=True, null=True, storage=s3.s3utils.MediaStorage(acl='private'), upload_to='seekrit/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
