# Generated by Django 2.2.2 on 2019-08-06 23:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experiment', '0017_remove_plate_numsubwells'),
        ('s3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivateImage',
            new_name='WellImage',
        ),
    ]
