# Generated by Django 2.2.6 on 2019-11-13 01:30

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import s3.models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefilejson',
            name='local_upload',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=s3.models.upload_local_path, validators=[django.core.validators.FileExtensionValidator(['json'])]),
        ),
    ]
