# Generated by Django 2.2.6 on 2019-12-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefilecsv',
            name='filetype',
            field=models.CharField(default='.csv', max_length=5),
        ),
        migrations.AlterField(
            model_name='privatefilejson',
            name='filetype',
            field=models.CharField(default='.json', max_length=5),
        ),
    ]
