# Generated by Django 2.2.6 on 2019-12-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0002_auto_20191216_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatefile',
            name='filename',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='privatefilecsv',
            name='filename',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='privatefilejson',
            name='filename',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='publicfile',
            name='filename',
            field=models.CharField(default='', max_length=100),
        ),
    ]
