# Generated by Django 2.2.2 on 2019-07-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0002_auto_20190730_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
