# Generated by Django 2.2.6 on 2019-11-15 21:37

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import s3.models
import s3.s3utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s3', '0002_auto_20191113_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateFileCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(blank=True, null=True, storage=s3.s3utils.PublicMediaStorage(), upload_to=s3.models.user_file_upload_path)),
                ('local_upload', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=s3.models.upload_local_path)),
                ('s3_fileName', models.CharField(default='', max_length=100)),
                ('local_fileName', models.CharField(default='', max_length=100)),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='privatefilejson',
            name='has_upload',
        ),
        migrations.RemoveConstraint(
            model_name='publicfile',
            name='has_upload',
        ),
        migrations.AddConstraint(
            model_name='privatefilejson',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, local_upload__in=['', None]), models.Q(_negated=True, upload__in=['', None]), _connector='OR'), name='privatefilejson_has_upload'),
        ),
        migrations.AddConstraint(
            model_name='publicfile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, local_upload__in=['', None]), models.Q(_negated=True, upload__in=['', None]), _connector='OR'), name='publicfile_has_upload'),
        ),
        migrations.AddField(
            model_name='privatefilecsv',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s3_privatefilecsv_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='privatefilecsv',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, local_upload__in=['', None]), models.Q(_negated=True, upload__in=['', None]), _connector='OR'), name='has_upload'),
        ),
    ]
