# Generated by Django 2.2.2 on 2019-08-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0003_wellimage_well_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellimage',
            old_name='well_name',
            new_name='file_name',
        ),
    ]
