# Generated by Django 2.2.2 on 2019-07-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0003_delete_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatefile',
            old_name='user',
            new_name='owner',
        ),
    ]
