# Generated by Django 2.2.11 on 2020-03-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0003_auto_20191216_2327'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='privatefilejson',
            name='endswith_json',
        ),
        migrations.AddConstraint(
            model_name='privatefilejson',
            constraint=models.CheckConstraint(check=models.Q(('local_upload__in', ['', None]), ('local_upload__endswith', '.json'), _connector='OR'), name='endswith_json'),
        ),
    ]
