# Generated by Django 2.2.6 on 2019-11-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0004_auto_20191115_2336'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='privatefilecsv',
            name='endswith_csv',
        ),
        migrations.AddConstraint(
            model_name='privatefilecsv',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, local_upload__in=['', None]), models.Q(_negated=True, local_upload__endswith='.csv')), name='endswith_csv'),
        ),
    ]
