# Generated by Django 2.2.2 on 2019-08-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0004_auto_20190730_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefile',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
    ]
