# Generated by Django 2.2.2 on 2019-08-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0005_auto_20190801_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatefile',
            name='bucket_key',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
