# Generated by Django 2.2.2 on 2019-08-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0006_privatefile_bucket_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefile',
            name='bucket_key',
            field=models.CharField(max_length=1000),
        ),
    ]
