# Generated by Django 2.2.6 on 2019-11-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0006_auto_20191115_2339'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='privatefilecsv',
            name='does_not_end_with_csv',
        ),
        migrations.AddConstraint(
            model_name='privatefilecsv',
            constraint=models.CheckConstraint(check=models.Q(('local_upload__in', ['', None]), models.Q(_negated=True, local_upload__endswith='.csv'), _connector='OR'), name='does_not_end_with_csv'),
        ),
    ]
