# Generated by Django 2.2.6 on 2019-11-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0007_auto_20191115_2340'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='privatefilecsv',
            name='has_upload',
        ),
        migrations.RemoveConstraint(
            model_name='privatefilecsv',
            name='does_not_end_with_csv',
        ),
        migrations.RemoveConstraint(
            model_name='privatefilejson',
            name='privatefilejson_has_upload',
        ),
        migrations.AddConstraint(
            model_name='privatefilecsv',
            constraint=models.CheckConstraint(check=models.Q(('local_upload__in', ['', None]), ('upload__in', ['', None])), name='has_upload'),
        ),
        migrations.AddConstraint(
            model_name='privatefilecsv',
            constraint=models.CheckConstraint(check=models.Q(('local_upload__in', ['', None]), ('local_upload__endswith', '.csv'), _connector='OR'), name='endswith_csv'),
        ),
        migrations.AddConstraint(
            model_name='privatefilejson',
            constraint=models.CheckConstraint(check=models.Q(('local_upload__in', ['', None]), ('upload__in', ['', None])), name='privatefilejson_has_upload'),
        ),
    ]
