# Generated by Django 2.2.6 on 2019-11-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0008_auto_20191115_2350'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='privatefilecsv',
            name='has_upload',
        ),
        migrations.RemoveConstraint(
            model_name='privatefilejson',
            name='privatefilejson_has_upload',
        ),
        migrations.AddConstraint(
            model_name='privatefilecsv',
            constraint=models.CheckConstraint(check=models.Q(('local_upload__in', ['', None]), ('upload__in', ['', None]), _negated=True), name='has_upload'),
        ),
        migrations.AddConstraint(
            model_name='privatefilejson',
            constraint=models.CheckConstraint(check=models.Q(('local_upload__in', ['', None]), ('upload__in', ['', None]), _negated=True), name='privatefilejson_has_upload'),
        ),
    ]
