# Generated by Django 2.2.6 on 2019-11-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0009_auto_20191115_2354'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='privatefilecsv',
            name='endswith_csv',
        ),
        migrations.AddConstraint(
            model_name='privatefilecsv',
            constraint=models.CheckConstraint(check=models.Q(local_upload__endswith='.csv'), name='endswith_csv'),
        ),
    ]
