# Generated by Django 2.2.6 on 2019-11-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0010_auto_20191116_0006'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='privatefilejson',
            name='endswith_json',
        ),
        migrations.AddConstraint(
            model_name='privatefilejson',
            constraint=models.CheckConstraint(check=models.Q(local_upload__endswith='.json'), name='endswith_json'),
        ),
    ]
