# Generated by Django 2.2.6 on 2019-11-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0011_auto_20191116_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatefile',
            name='local_fileName',
        ),
        migrations.RemoveField(
            model_name='privatefile',
            name='s3_fileName',
        ),
        migrations.RemoveField(
            model_name='privatefilecsv',
            name='local_fileName',
        ),
        migrations.RemoveField(
            model_name='privatefilecsv',
            name='s3_fileName',
        ),
        migrations.RemoveField(
            model_name='privatefilejson',
            name='local_fileName',
        ),
        migrations.RemoveField(
            model_name='privatefilejson',
            name='s3_fileName',
        ),
        migrations.RemoveField(
            model_name='publicfile',
            name='local_fileName',
        ),
        migrations.RemoveField(
            model_name='publicfile',
            name='s3_fileName',
        ),
        migrations.AddField(
            model_name='privatefile',
            name='filetype',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='privatefilecsv',
            name='filetype',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='privatefilejson',
            name='filetype',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='publicfile',
            name='filetype',
            field=models.CharField(default='', max_length=5),
        ),
    ]
