# Generated by Django 2.2.6 on 2019-11-19 01:55

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import s3.models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0012_auto_20191118_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefilecsv',
            name='local_upload',
            field=models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=s3.models.upload_local_path, validators=[django.core.validators.FileExtensionValidator(['csv'])]),
            preserve_default=False,
        ),
    ]
