# Generated by Django 2.2.6 on 2019-11-19 01:56

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import s3.models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0013_auto_20191119_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefilecsv',
            name='local_upload',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=s3.models.upload_local_path, validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
