# Generated by Django 2.2.6 on 2019-12-03 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='primary_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
