# Generated by Django 2.2.2 on 2019-10-18 20:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemicalName', models.CharField(blank=True, max_length=300, null=True)),
                ('chemicalFormula', models.CharField(default='', max_length=100)),
                ('wellLocation', models.CharField(blank=True, max_length=4, null=True)),
                ('zinc_id', models.CharField(max_length=30, unique=True)),
                ('smiles', models.CharField(blank=True, max_length=300, null=True)),
                ('zincURL', models.URLField(blank=True, null=True)),
                ('molWeight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('concentration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purity', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(default='', max_length=300)),
                ('isCommerical', models.BooleanField(default=False)),
                ('sourceURL', models.URLField(blank=True, null=True)),
                ('isTemplate', models.BooleanField(default=False)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('compounds', models.ManyToManyField(blank=True, related_name='libraries', to='import_ZINC.Compound')),
                ('groups', models.ManyToManyField(blank=True, related_name='group_libraries', to='auth.Group')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
