# Generated by Django 2.1.1 on 2019-06-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_ZINC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='library',
            name='supplier',
            field=models.CharField(default='', max_length=100),
        ),
    ]
