# Generated by Django 2.2.2 on 2019-09-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_ZINC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
