# Generated by Django 2.2.2 on 2019-08-19 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_ZINC', '0002_compound_welllocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='commonName',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='nameInternal',
        ),
        migrations.AddField(
            model_name='compound',
            name='purity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
