# Generated by Django 2.1.1 on 2019-06-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_ZINC', '0002_auto_20190628_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='zinc_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
