# Generated by Django 2.1.1 on 2019-06-28 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('import_ZINC', '0003_auto_20190628_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='zincURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='isCommerical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='library',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='library',
            name='sourceURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='libraries', to='auth.Group'),
        ),
    ]
