# Generated by Django 2.2.2 on 2019-06-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_ZINC', '0004_auto_20190628_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='library',
        ),
        migrations.AddField(
            model_name='library',
            name='compounds',
            field=models.ManyToManyField(blank=True, null=True, related_name='libraries', to='import_ZINC.Compound'),
        ),
    ]
