# Generated by Django 2.2.2 on 2019-08-19 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_ZINC', '0004_auto_20190819_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='purity',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
