# Generated by Django 2.2.2 on 2019-06-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_ZINC', '0005_auto_20190628_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
