# Generated by Django 2.2.2 on 2019-06-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_ZINC', '0006_compound_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='compounds',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='import_ZINC.Compound'),
        ),
        migrations.AlterField(
            model_name='library',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='auth.Group'),
        ),
    ]
