# Generated by Django 2.2.2 on 2019-07-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_ZINC', '0007_auto_20190630_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='chemicalName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='nameInternal',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='smiles',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
