# Generated by Django 2.2.2 on 2019-08-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_ZINC', '0007_auto_20190826_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='zinc_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
