# Generated by Django 2.2.2 on 2019-08-01 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import s3.s3utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ImageField(storage=s3.s3utils.PrivateMediaStorage(), upload_to='')),
                ('bucket_key', models.CharField(max_length=1000, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
