# Generated by Django 2.2.2 on 2019-09-26 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0001_initial'),
        ('experiment', '0008_auto_20190823_2106'),
        ('xtal_img', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropImage',
            fields=[
                ('privatefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='s3.PrivateFile')),
                ('well_name', models.CharField(max_length=10)),
                ('plate_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_images', to='experiment.Plate')),
            ],
            bases=('s3.privatefile',),
        ),
        migrations.DeleteModel(
            name='S3_WellImage',
        ),
    ]
