# Generated by Django 2.2.2 on 2019-08-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtal_img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellimage',
            name='upload',
            field=models.ImageField(editable=False, upload_to=''),
        ),
    ]
