# Generated by Django 2.2.6 on 2019-11-11 22:35

import django.core.files.storage
from django.db import migrations, models
import xtal_img.models


class Migration(migrations.Migration):

    dependencies = [
        ('xtal_img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropimage',
            name='local_upload',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=xtal_img.models.drop_image_upload_path_local),
        ),
    ]
