# Generated by Django 2.2.2 on 2019-08-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtal_img', '0002_auto_20190801_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellimage',
            name='upload',
            field=models.ImageField(upload_to=''),
        ),
    ]
