# Generated by Django 2.2.2 on 2019-10-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtal_img', '0002_auto_20191024_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropimage',
            name='file_name',
            field=models.CharField(max_length=5),
        ),
    ]
