# Generated by Django 2.2.2 on 2019-10-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtal_img', '0002_auto_20191003_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropimages3',
            old_name='plate_from',
            new_name='plate',
        ),
    ]
