# Generated by Django 2.2.2 on 2019-10-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtal_img', '0003_auto_20191024_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dropimage',
            options={'ordering': ('file_name',)},
        ),
    ]
