# Generated by Django 2.2.2 on 2019-08-01 17:12

from django.db import migrations, models
import s3.s3utils
import xtal_img.models


class Migration(migrations.Migration):

    dependencies = [
        ('xtal_img', '0003_auto_20190801_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellimage',
            name='upload',
            field=models.ImageField(storage=s3.s3utils.PrivateMediaStorage(), upload_to=xtal_img.models.upload_path),
        ),
    ]
