# Generated by Django 2.2.2 on 2019-10-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtal_img', '0003_auto_20191003_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DropImageS3',
        ),
    ]
