# Generated by Django 2.2.2 on 2019-10-03 18:58

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import s3.models
import s3.s3utils
import uuid
import xtal_img.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experiment', '0005_soak_targetwellradius'),
        ('xtal_img', '0004_delete_dropimages3'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropImageS3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('upload', models.ImageField(storage=s3.s3utils.PrivateMediaStorage(), upload_to=s3.models.upload_path)),
                ('well_name', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_images_s3', to=settings.AUTH_USER_MODEL)),
                ('plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_images_s3', to='experiment.Plate')),
            ],
        ),
        migrations.CreateModel(
            name='DropImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/'), upload_to=xtal_img.models.upload_local_path)),
                ('well_name', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_images', to=settings.AUTH_USER_MODEL)),
                ('plate_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_images', to='experiment.Plate')),
            ],
        ),
    ]
