# Generated by Django 2.2.2 on 2019-10-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtal_img', '0004_auto_20191024_2056'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dropimage',
            constraint=models.UniqueConstraint(fields=('plate_id', 'file_name'), name='unique_filename_per_plate'),
        ),
    ]
