# Generated by Django 2.2.2 on 2019-10-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtal_img', '0005_dropimage_dropimages3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropimage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='dropimage',
            name='plate_from',
        ),
    ]
