# Generated by Django 2.2.2 on 2019-10-03 19:45

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import xtal_img.models


class Migration(migrations.Migration):

    dependencies = [
        ('experiment', '0005_soak_targetwellradius'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xtal_img', '0006_auto_20191003_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropimage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dropimage',
            name='plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_images', to='experiment.Plate'),
        ),
        migrations.AlterField(
            model_name='dropimage',
            name='upload',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=xtal_img.models.upload_local_path),
        ),
    ]
